### ISSUE TITLE
Доработка документации

### ISSUE THREAD

**Issue by evilslon** [alsav/stm8-soldering-station-controller#1]
Я, как и Вы, столкнулся с тем, что мой паяльник Tomizawa FZ-880C умер от скачка сетевого напряжения. В результате проверки, я диагностировал КЗ в процессоре 46R01, поэтому Ваш проект мне показался очень интересен и я решил повторить Ваш опыт. Но, судя по всему, Вы не предполагали, что кто-то на это решится и оставили документацию в недоработанном состоянии. Схемы подключения создаваемой платы нет, а посему многое непонятно. С какого, например, вывода STM8 берётся PWM сигнал, идущий на 10 вывод выпаянной микросхемы (а затем на R11 и базу P2)? Укажите, пожалуйста, ёмкость конденсатора C2 (подключен к выводу Vcap) и C1 (фильтр питания) на Вашей платке. Расскажите поподробнее про доработку системы питания микроконтроллера. Если не сложно, напишите свой email для связи. Заранее спасибо!

**Comment by alsav** [comment]
Приветствую!

Добавил в проект схему подключения платы (файл board_pinout.jpg). Номиналы конденсаторов указал там же, все взяты из даташита на МК. HEAT_CTL (PWM), ZERO_DETECT и TEMP_SENSE подключаются к 46R01, в скобках указаны номера выводов. SWIM и NRST - для прошивки МК. UART_TX и RESERVED в рабочем варианте не используются. Остальное думаю понятно.

Про доработку схемы питания немного есть в IMG1.jpg. Изначально схема состояла из конденсатора C2, диодов D3 и D4 и стабилитрона Z1 скорее всего на 3.3 или 5В. Под выводами R24 оказалась дорожка. Таким образом после C2 ток ничем не ограничивался, что вызвало пробой Z1 и U1. Чтобы исправить ситуацию, удалил дорожку под R24, увеличил сопротивление до 150Ом. Z1 заменил на TL431A с резисторным делителем на 3.3В. Номиналы резисторов 10 и 30КОм, сделаны навесным монтажом. IMG4.jpg - что получилось в результате.

Если что-то будет не понятно - спрашивайте al.sadakov<собачка>gmail.com. 
На всякий случай предупреждаю: т.к. схема питания логики не имеет гальванической развязки, при прошивке МК ОБЯЗАТЕЛЬНО отключать паяльник от сети! Питание при прошивке берется с программатора.
Удачи!
